// <auto-generated />
using System;
using Manage.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Manage.API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220721095537_Migrations")]
    partial class Migrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Manage.Model.Models.HuAllowance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Activeflg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("activeflg");

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("code");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("created_time");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("last_update_time");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("hu_allowance");
                });

            modelBuilder.Entity("Manage.Model.Models.HuBank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Activeflg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("activeflg");

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("code");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("created_time");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("last_update_time");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("hu_bank");
                });

            modelBuilder.Entity("Manage.Model.Models.HuBankBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Activeflg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("activeflg");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<int?>("BankId")
                        .HasColumnType("int")
                        .HasColumnName("bank_id");

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("code");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("created_time");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("last_update_time");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_updated_by");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BankId" }, "IX_hu_bank_branch_bank_id");

                    b.ToTable("hu_bank_branch");
                });

            modelBuilder.Entity("Manage.Model.Models.HuContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Activeflg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("activeflg");

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("code");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("created_time");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("last_update_time");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_updated_by");

                    b.Property<double?>("Money")
                        .HasColumnType("float")
                        .HasColumnName("money");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("note");

                    b.Property<int?>("NumberOfMonth")
                        .HasColumnType("int")
                        .HasColumnName("number_of_month");

                    b.HasKey("Id");

                    b.ToTable("hu_contract");
                });

            modelBuilder.Entity("Manage.Model.Models.HuContractAllowance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Activeflg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("activeflg");

                    b.Property<int?>("AllwanceId")
                        .HasColumnType("int")
                        .HasColumnName("allwance_id");

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("code");

                    b.Property<int?>("ContractId")
                        .HasColumnType("int")
                        .HasColumnName("contract_id");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("created_time");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("last_update_time");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_updated_by");

                    b.Property<double?>("Money")
                        .HasColumnType("float")
                        .HasColumnName("money");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AllwanceId" }, "IX_hu_Contract_allowance_allwance_id");

                    b.HasIndex(new[] { "ContractId" }, "IX_hu_Contract_allowance_contract_id");

                    b.ToTable("hu_Contract_allowance");
                });

            modelBuilder.Entity("Manage.Model.Models.HuContractualBenefit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Activeflg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("activeflg");

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("code");

                    b.Property<int?>("ContractId")
                        .HasColumnType("int")
                        .HasColumnName("contract_id");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("created_time");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("last_update_time");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_updated_by");

                    b.Property<double?>("Money")
                        .HasColumnType("float")
                        .HasColumnName("money");

                    b.Property<int?>("WelfaceId")
                        .HasColumnType("int")
                        .HasColumnName("welface_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ContractId" }, "IX_hu_contractual_benefits_contract_id");

                    b.HasIndex(new[] { "WelfaceId" }, "IX_hu_contractual_benefits_welface_id");

                    b.ToTable("hu_contractual_benefits");
                });

            modelBuilder.Entity("Manage.Model.Models.HuDistrict", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Activeflg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("activeflg");

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("code");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("created_time");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("last_update_time");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("ProvinceId")
                        .HasColumnType("int")
                        .HasColumnName("province_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ProvinceId" }, "IX_hu_district_province_id");

                    b.ToTable("hu_district");
                });

            modelBuilder.Entity("Manage.Model.Models.HuEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("code");

                    b.Property<int?>("ContractId")
                        .HasColumnType("int")
                        .HasColumnName("contract_id");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("created_time");

                    b.Property<string>("DirectManager")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("direct_manager");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("first_name");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<int?>("ItimeId")
                        .HasColumnType("int")
                        .HasColumnName("itime_id");

                    b.Property<DateTime?>("JoinDate")
                        .HasColumnType("datetime")
                        .HasColumnName("join_date");

                    b.Property<string>("LastName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("last_update_time");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_updated_by");

                    b.Property<DateTime?>("LastWorkingDay")
                        .HasColumnType("datetime")
                        .HasColumnName("last_working_day");

                    b.Property<int?>("LastWorkingId")
                        .HasColumnType("int")
                        .HasColumnName("last_working_id");

                    b.Property<int?>("OrgId")
                        .HasColumnType("int")
                        .HasColumnName("org_id");

                    b.Property<int?>("TitleId")
                        .HasColumnType("int")
                        .HasColumnName("title_id");

                    b.Property<bool?>("WorkStatus")
                        .HasColumnType("bit")
                        .HasColumnName("work_status");

                    b.Property<int?>("WorkingId")
                        .HasColumnType("int")
                        .HasColumnName("working_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ContractId" }, "IX_hu_employee_contract_id");

                    b.HasIndex(new[] { "OrgId" }, "IX_hu_employee_org_id");

                    b.HasIndex(new[] { "TitleId" }, "IX_hu_employee_title_id");

                    b.ToTable("hu_employee");
                });

            modelBuilder.Entity("Manage.Model.Models.HuEmployeeCv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BankNumber")
                        .HasColumnType("int")
                        .HasColumnName("bank_number");

                    b.Property<string>("ClothesSize")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("clothes_size");

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("code");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("created_time");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Ethnic")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ethnic");

                    b.Property<bool?>("HealthCondition")
                        .HasColumnType("bit")
                        .HasColumnName("health_condition");

                    b.Property<int?>("HospitalId")
                        .HasColumnType("int")
                        .HasColumnName("hospital_id");

                    b.Property<int?>("IdCard")
                        .HasColumnType("int")
                        .HasColumnName("id_card");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("last_update_time");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("name");

                    b.Property<string>("PermanentAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("permanent_address");

                    b.Property<string>("PlaceOfBirth")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Place_of_birth");

                    b.Property<string>("Reiligion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("reiligion");

                    b.Property<bool?>("Sex")
                        .HasColumnType("bit")
                        .HasColumnName("sex");

                    b.Property<string>("TemporaryAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("temporary_address");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "HospitalId" }, "IX_hu_employee_cv_hospital_id");

                    b.ToTable("hu_employee_cv");
                });

            modelBuilder.Entity("Manage.Model.Models.HuEmployeeEducation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Activeflg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("activeflg");

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("code");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("created_time");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<DateTime?>("FinsishDate")
                        .HasColumnType("datetime")
                        .HasColumnName("finsish_date");

                    b.Property<DateTime?>("FisrtDate")
                        .HasColumnType("datetime")
                        .HasColumnName("fisrt_date");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("last_update_time");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("note");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "EmployeeId" }, "IX_hu_employee_education_employee_id");

                    b.ToTable("hu_employee_education");
                });

            modelBuilder.Entity("Manage.Model.Models.HuFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("code");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("created_time");

                    b.Property<string>("District")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("district");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<string>("FirstName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("first_name");

                    b.Property<string>("FullName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("full_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("last_update_time");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("Nation")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("nation");

                    b.Property<string>("Phonenumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("phonenumber");

                    b.Property<string>("Province")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("province");

                    b.Property<string>("Relationship")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("relationship");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "EmployeeId" }, "IX_hu_family_employee_id");

                    b.ToTable("hu_family");
                });

            modelBuilder.Entity("Manage.Model.Models.HuHospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Activeflg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("activeflg");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("code");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("created_time");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("last_update_time");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("hu_hospital");
                });

            modelBuilder.Entity("Manage.Model.Models.HuNation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Activeflg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("activeflg");

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("code");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("created_time");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("last_update_time");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("hu_nation");
                });

            modelBuilder.Entity("Manage.Model.Models.HuOrgTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("code");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("created_time");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("last_update_time");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_updated_by");

                    b.Property<int?>("OrgId")
                        .HasColumnType("int");

                    b.Property<int?>("TitleId")
                        .HasColumnType("int")
                        .HasColumnName("title_id");

                    b.HasKey("Id");

                    b.ToTable("hu_org_title");
                });

            modelBuilder.Entity("Manage.Model.Models.HuOrganization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Activeflg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("activeflg");

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("code");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("created_time");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("last_update_time");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("OrderNumber")
                        .HasColumnType("int")
                        .HasColumnName("order_number");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.HasKey("Id");

                    b.ToTable("hu_organization");
                });

            modelBuilder.Entity("Manage.Model.Models.HuProvince", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Activeflg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("activeflg");

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("code");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("created_time");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("last_update_time");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("NationId")
                        .HasColumnType("int")
                        .HasColumnName("nation_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NationId" }, "IX_hu_province_nation_id");

                    b.ToTable("hu_province");
                });

            modelBuilder.Entity("Manage.Model.Models.HuSalaryRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("code");

                    b.Property<int?>("ContracId")
                        .HasColumnType("int")
                        .HasColumnName("contrac_id");

                    b.Property<int?>("ContractAllwanceId")
                        .HasColumnType("int")
                        .HasColumnName("contract_allwance_id");

                    b.Property<int?>("ContractWelfaceId")
                        .HasColumnType("int")
                        .HasColumnName("contract_welface_id");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("created_time");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("last_update_time");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_updated_by");

                    b.Property<double?>("Money")
                        .HasColumnType("float")
                        .HasColumnName("money");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ContracId" }, "IX_hu_salary_records_contrac_id");

                    b.HasIndex(new[] { "ContractAllwanceId" }, "IX_hu_salary_records_contract_allwance_id");

                    b.HasIndex(new[] { "ContractWelfaceId" }, "IX_hu_salary_records_contract_welface_id");

                    b.HasIndex(new[] { "EmployeeId" }, "IX_hu_salary_records_employee_id");

                    b.ToTable("hu_salary_records");
                });

            modelBuilder.Entity("Manage.Model.Models.HuTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("code");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("created_time");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("last_update_time");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("hu_title");
                });

            modelBuilder.Entity("Manage.Model.Models.HuTypeOfContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Activeflg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("activeflg");

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("code");

                    b.Property<int?>("ContractId")
                        .HasColumnType("int")
                        .HasColumnName("contract_id");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("created_time");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("last_update_time");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<int?>("NumberOfMonth")
                        .HasColumnType("int")
                        .HasColumnName("number_of_month");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ContractId" }, "IX_hu_type_of_contract_contract_id");

                    b.ToTable("hu_type_of_contract");
                });

            modelBuilder.Entity("Manage.Model.Models.HuWard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Activeflg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("activeflg");

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("code");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("created_time");

                    b.Property<int?>("DistricId")
                        .HasColumnType("int")
                        .HasColumnName("distric_id");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("last_update_time");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DistricId" }, "IX_hu_ward_distric_id");

                    b.ToTable("hu_ward");
                });

            modelBuilder.Entity("Manage.Model.Models.HuWelface", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Activeflg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("activeflg");

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("code");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("created_time");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("last_update_time");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("hu_welface");
                });

            modelBuilder.Entity("Manage.Model.Models.OtherList", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Activeflg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("activeflg");

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("code");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("created_time");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("last_update_time");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_updated_by");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("type_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TypeId" }, "IX_other_list_type_id");

                    b.ToTable("other_list");
                });

            modelBuilder.Entity("Manage.Model.Models.OtherListType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("code");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("created_time");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("last_update_time");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_updated_by");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("other_list_type");
                });

            modelBuilder.Entity("Manage.Model.Models.SeUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Code");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Created_by");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_time");

                    b.Property<DateTime?>("LastUpdateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("Last_update_time");

                    b.Property<string>("LastUpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Last_updated_by");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Role");

                    b.Property<string>("activeflg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ActiveFlg");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Password");

                    b.Property<string>("token")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Token");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.ToTable("Se_User");
                });

            modelBuilder.Entity("Manage.Model.Models.HuBankBranch", b =>
                {
                    b.HasOne("Manage.Model.Models.HuBank", "Bank")
                        .WithMany("HuBankBranches")
                        .HasForeignKey("BankId");

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("Manage.Model.Models.HuContractAllowance", b =>
                {
                    b.HasOne("Manage.Model.Models.HuAllowance", "Allwance")
                        .WithMany("HuContractAllowances")
                        .HasForeignKey("AllwanceId");

                    b.HasOne("Manage.Model.Models.HuContract", "Contract")
                        .WithMany("HuContractAllowances")
                        .HasForeignKey("ContractId");

                    b.Navigation("Allwance");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Manage.Model.Models.HuContractualBenefit", b =>
                {
                    b.HasOne("Manage.Model.Models.HuContract", "Contract")
                        .WithMany("HuContractualBenefits")
                        .HasForeignKey("ContractId");

                    b.HasOne("Manage.Model.Models.HuWelface", "Welface")
                        .WithMany("HuContractualBenefits")
                        .HasForeignKey("WelfaceId");

                    b.Navigation("Contract");

                    b.Navigation("Welface");
                });

            modelBuilder.Entity("Manage.Model.Models.HuDistrict", b =>
                {
                    b.HasOne("Manage.Model.Models.HuProvince", "Province")
                        .WithMany("HuDistricts")
                        .HasForeignKey("ProvinceId");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Manage.Model.Models.HuEmployee", b =>
                {
                    b.HasOne("Manage.Model.Models.HuContract", "Contract")
                        .WithMany("HuEmployees")
                        .HasForeignKey("ContractId");

                    b.HasOne("Manage.Model.Models.HuOrgTitle", "Org")
                        .WithMany("HuEmployees")
                        .HasForeignKey("OrgId");

                    b.HasOne("Manage.Model.Models.HuTitle", "Title")
                        .WithMany("HuEmployees")
                        .HasForeignKey("TitleId");

                    b.Navigation("Contract");

                    b.Navigation("Org");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Manage.Model.Models.HuEmployeeCv", b =>
                {
                    b.HasOne("Manage.Model.Models.HuHospital", "Hospital")
                        .WithMany("HuEmployeeCvs")
                        .HasForeignKey("HospitalId");

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("Manage.Model.Models.HuEmployeeEducation", b =>
                {
                    b.HasOne("Manage.Model.Models.HuEmployee", "Employee")
                        .WithMany("HuEmployeeEducations")
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Manage.Model.Models.HuFamily", b =>
                {
                    b.HasOne("Manage.Model.Models.HuEmployee", "Employee")
                        .WithMany("HuFamilies")
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Manage.Model.Models.HuProvince", b =>
                {
                    b.HasOne("Manage.Model.Models.HuNation", "Nation")
                        .WithMany("HuProvinces")
                        .HasForeignKey("NationId");

                    b.Navigation("Nation");
                });

            modelBuilder.Entity("Manage.Model.Models.HuSalaryRecord", b =>
                {
                    b.HasOne("Manage.Model.Models.HuContract", "Contrac")
                        .WithMany("HuSalaryRecords")
                        .HasForeignKey("ContracId");

                    b.HasOne("Manage.Model.Models.HuContractAllowance", "ContractAllwance")
                        .WithMany("HuSalaryRecords")
                        .HasForeignKey("ContractAllwanceId");

                    b.HasOne("Manage.Model.Models.HuWelface", "ContractWelface")
                        .WithMany("HuSalaryRecords")
                        .HasForeignKey("ContractWelfaceId");

                    b.HasOne("Manage.Model.Models.HuEmployee", "Employee")
                        .WithMany("HuSalaryRecords")
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Contrac");

                    b.Navigation("ContractAllwance");

                    b.Navigation("ContractWelface");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Manage.Model.Models.HuTypeOfContract", b =>
                {
                    b.HasOne("Manage.Model.Models.HuContract", "Contract")
                        .WithMany("HuTypeOfContracts")
                        .HasForeignKey("ContractId");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Manage.Model.Models.HuWard", b =>
                {
                    b.HasOne("Manage.Model.Models.HuDistrict", "Distric")
                        .WithMany("HuWards")
                        .HasForeignKey("DistricId");

                    b.Navigation("Distric");
                });

            modelBuilder.Entity("Manage.Model.Models.OtherList", b =>
                {
                    b.HasOne("Manage.Model.Models.OtherListType", "IdNavigation")
                        .WithOne("OtherList")
                        .HasForeignKey("Manage.Model.Models.OtherList", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Manage.Model.Models.HuTitle", "Type")
                        .WithMany("OtherLists")
                        .HasForeignKey("TypeId");

                    b.Navigation("IdNavigation");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Manage.Model.Models.HuAllowance", b =>
                {
                    b.Navigation("HuContractAllowances");
                });

            modelBuilder.Entity("Manage.Model.Models.HuBank", b =>
                {
                    b.Navigation("HuBankBranches");
                });

            modelBuilder.Entity("Manage.Model.Models.HuContract", b =>
                {
                    b.Navigation("HuContractAllowances");

                    b.Navigation("HuContractualBenefits");

                    b.Navigation("HuEmployees");

                    b.Navigation("HuSalaryRecords");

                    b.Navigation("HuTypeOfContracts");
                });

            modelBuilder.Entity("Manage.Model.Models.HuContractAllowance", b =>
                {
                    b.Navigation("HuSalaryRecords");
                });

            modelBuilder.Entity("Manage.Model.Models.HuDistrict", b =>
                {
                    b.Navigation("HuWards");
                });

            modelBuilder.Entity("Manage.Model.Models.HuEmployee", b =>
                {
                    b.Navigation("HuEmployeeEducations");

                    b.Navigation("HuFamilies");

                    b.Navigation("HuSalaryRecords");
                });

            modelBuilder.Entity("Manage.Model.Models.HuHospital", b =>
                {
                    b.Navigation("HuEmployeeCvs");
                });

            modelBuilder.Entity("Manage.Model.Models.HuNation", b =>
                {
                    b.Navigation("HuProvinces");
                });

            modelBuilder.Entity("Manage.Model.Models.HuOrgTitle", b =>
                {
                    b.Navigation("HuEmployees");
                });

            modelBuilder.Entity("Manage.Model.Models.HuProvince", b =>
                {
                    b.Navigation("HuDistricts");
                });

            modelBuilder.Entity("Manage.Model.Models.HuTitle", b =>
                {
                    b.Navigation("HuEmployees");

                    b.Navigation("OtherLists");
                });

            modelBuilder.Entity("Manage.Model.Models.HuWelface", b =>
                {
                    b.Navigation("HuContractualBenefits");

                    b.Navigation("HuSalaryRecords");
                });

            modelBuilder.Entity("Manage.Model.Models.OtherListType", b =>
                {
                    b.Navigation("OtherList");
                });
#pragma warning restore 612, 618
        }
    }
}
